### ISSUE TITLE
Compressed image format option

### ISSUE THREAD

**Issue by JJBUT** [ut-amrl/spinnaker_ros_interface#3]
https://github.com/ut-amrl/spinnaker_ros_interface/blob/4765be4f31bcfd260862a25168f5ef5544afa0d4/src/spinnaker_ros_interface_main.cc#L314

@joydeep-b  I haven't dug into this code too much so I want to consult you from the very start. My question is: do you see simple path to allow for publishing of `sensor_msgs::Image` and `sensor_msgs::ImageCompressed`?  Sadegh and I think that is a valuable feature and would be nice to have as a parameter of the wrapper. Compressed images make the bagfiles much smaller. 

Right now I can use the [image_transport](https://wiki.ros.org/image_transport) to compress the images but this is not an extensible or long term solution.

**Comment by joydeep-b** [comment]
Image transport seems the correct way to address this at the publisher end - why do you say it is not a long-term solution?

If you prefer to implement compression manually, you can use a direct compression API (e.g. [libjpeg-turbo](https://github.com/libjpeg-turbo/libjpeg-turbo)) 

For compressing raw images, there is a better way than to directly compress a mosaiced image - we can talk about this in person.

**Comment by JJBUT** [comment]
https://github.com/ut-amrl/spinnaker_ros_interface/pull/4
